module Falco.Markup.Html

[<AutoOpen>]
module Text =
    let _empty = Text.empty
    let _enc = Text.enc
    let _raw = Text.raw
    let _rawf = Text.rawf
    let _comment = Text.comment

[<AutoOpen>]
module Elem =
    let _html = Elem.html
    let _base = Elem.base'
    let _head = Elem.head
    let _link = Elem.link
    let _meta = Elem.meta
    let _style = Elem.style
    let _title = Elem.title
    let _body = Elem.body
    let _address = Elem.address
    let _article = Elem.article
    let _aside = Elem.aside
    let _footer = Elem.footer
    let _header = Elem.header
    let _h1 = Elem.h1
    let _h2 = Elem.h2
    let _h3 = Elem.h3
    let _h4 = Elem.h4
    let _h5 = Elem.h5
    let _h6 = Elem.h6
    let _main = Elem.main
    let _nav = Elem.nav
    let _section = Elem.section
    let _blockquote = Elem.blockquote
    let _dd = Elem.dd
    let _div = Elem.div
    let _dl = Elem.dl
    let _dt = Elem.dt
    let _figcaption = Elem.figcaption
    let _figure = Elem.figure
    let _hr = Elem.hr
    let _li = Elem.li
    let _menu = Elem.menu
    let _ol = Elem.ol
    let _p = Elem.p
    let _pre = Elem.pre
    let _ul = Elem.ul
    let _a = Elem.a
    let _abbr = Elem.abbr
    let _b = Elem.b
    let _bdi = Elem.bdi
    let _bdo = Elem.bdo
    let _br = Elem.br
    let _cite = Elem.cite
    let _code = Elem.code
    let _data = Elem.data
    let _dfn = Elem.dfn
    let _em = Elem.em
    let _i = Elem.i
    let _kbd = Elem.kbd
    let _mark = Elem.mark
    let _q = Elem.q
    let _rp = Elem.rp
    let _rt = Elem.rt
    let _ruby = Elem.ruby
    let _s = Elem.s
    let _samp = Elem.samp
    let _small = Elem.small
    let _span = Elem.span
    let _strong = Elem.strong
    let _sub = Elem.sub
    let _sup = Elem.sup
    let _time = Elem.time
    let _u = Elem.u
    let _var = Elem.var
    let _wbr = Elem.wbr
    let _area = Elem.area
    let _audio = Elem.audio
    let _img = Elem.img
    let _map = Elem.map
    let _track = Elem.track
    let _video = Elem.video
    let _embed = Elem.embed
    let _iframe = Elem.iframe
    let _object = Elem.object
    let _picture = Elem.picture
    let _portal = Elem.portal
    let _source = Elem.source
    let _canvas = Elem.canvas
    let _noscript = Elem.noscript
    let _script = Elem.script
    let _del = Elem.del
    let _ins = Elem.ins
    let _caption = Elem.caption
    let _col = Elem.col
    let _colgroup = Elem.colgroup
    let _table = Elem.table
    let _tbody = Elem.tbody
    let _td = Elem.td
    let _tfoot = Elem.tfoot
    let _th = Elem.th
    let _thead = Elem.thead
    let _tr = Elem.tr
    let _button = Elem.button
    let _datalist = Elem.datalist
    let _fieldset = Elem.fieldset
    let _form = Elem.form
    let _input = Elem.input
    let _label = Elem.label
    let _legend = Elem.legend
    let _meter = Elem.meter
    let _optgroup = Elem.optgroup
    let _option = Elem.option
    let _output = Elem.output
    let _progress = Elem.progress
    let _select = Elem.select
    let _textarea = Elem.textarea
    let _details = Elem.details
    let _dialog = Elem.dialog
    let _summary = Elem.summary
    let _slot = Elem.slot
    let _template = Elem.template
    let _math = Elem.math
    let _svg = Elem.svg

    let _html' : XmlNode list -> XmlNode = Elem.html []
    let _head' : XmlNode list -> XmlNode = Elem.head []
    let _style' : XmlNode list -> XmlNode = Elem.style []
    let _title' : XmlNode list -> XmlNode = Elem.title []
    let _body' : XmlNode list -> XmlNode = Elem.body []
    let _address' : XmlNode list -> XmlNode = Elem.address []
    let _article' : XmlNode list -> XmlNode = Elem.article []
    let _aside' : XmlNode list -> XmlNode = Elem.aside []
    let _footer' : XmlNode list -> XmlNode = Elem.footer []
    let _header' : XmlNode list -> XmlNode = Elem.header []
    let _h1' : XmlNode list -> XmlNode = Elem.h1 []
    let _h2' : XmlNode list -> XmlNode = Elem.h2 []
    let _h3' : XmlNode list -> XmlNode = Elem.h3 []
    let _h4' : XmlNode list -> XmlNode = Elem.h4 []
    let _h5' : XmlNode list -> XmlNode = Elem.h5 []
    let _h6' : XmlNode list -> XmlNode = Elem.h6 []
    let _main' : XmlNode list -> XmlNode = Elem.main []
    let _nav' : XmlNode list -> XmlNode = Elem.nav []
    let _section' : XmlNode list -> XmlNode = Elem.section []
    let _blockquote' : XmlNode list -> XmlNode = Elem.blockquote []
    let _dd' : XmlNode list -> XmlNode = Elem.dd []
    let _div' : XmlNode list -> XmlNode = Elem.div []
    let _dl' : XmlNode list -> XmlNode = Elem.dl []
    let _dt' : XmlNode list -> XmlNode = Elem.dt []
    let _figcaption' : XmlNode list -> XmlNode = Elem.figcaption []
    let _figure' : XmlNode list -> XmlNode = Elem.figure []
    let _li' : XmlNode list -> XmlNode = Elem.li []
    let _menu' : XmlNode list -> XmlNode = Elem.menu []
    let _ol' : XmlNode list -> XmlNode = Elem.ol []
    let _p' : XmlNode list -> XmlNode = Elem.p []
    let _pre' : XmlNode list -> XmlNode = Elem.pre []
    let _ul' : XmlNode list -> XmlNode = Elem.ul []
    let _a' : XmlNode list -> XmlNode = Elem.a []
    let _abbr' : XmlNode list -> XmlNode = Elem.abbr []
    let _b' : XmlNode list -> XmlNode = Elem.b []
    let _bdi' : XmlNode list -> XmlNode = Elem.bdi []
    let _bdo' : XmlNode list -> XmlNode = Elem.bdo []
    let _cite' : XmlNode list -> XmlNode = Elem.cite []
    let _code' : XmlNode list -> XmlNode = Elem.code []
    let _data' : XmlNode list -> XmlNode = Elem.data []
    let _dfn' : XmlNode list -> XmlNode = Elem.dfn []
    let _em' : XmlNode list -> XmlNode = Elem.em []
    let _i' : XmlNode list -> XmlNode = Elem.i []
    let _kbd' : XmlNode list -> XmlNode = Elem.kbd []
    let _mark' : XmlNode list -> XmlNode = Elem.mark []
    let _q' : XmlNode list -> XmlNode = Elem.q []
    let _rp' : XmlNode list -> XmlNode = Elem.rp []
    let _rt' : XmlNode list -> XmlNode = Elem.rt []
    let _ruby' : XmlNode list -> XmlNode = Elem.ruby []
    let _s' : XmlNode list -> XmlNode = Elem.s []
    let _samp' : XmlNode list -> XmlNode = Elem.samp []
    let _small' : XmlNode list -> XmlNode = Elem.small []
    let _span' : XmlNode list -> XmlNode = Elem.span []
    let _strong' : XmlNode list -> XmlNode = Elem.strong []
    let _sub' : XmlNode list -> XmlNode = Elem.sub []
    let _sup' : XmlNode list -> XmlNode = Elem.sup []
    let _time' : XmlNode list -> XmlNode = Elem.time []
    let _u' : XmlNode list -> XmlNode = Elem.u []
    let _var' : XmlNode list -> XmlNode = Elem.var []
    let _area' : XmlNode list -> XmlNode = Elem.area []
    let _audio' : XmlNode list -> XmlNode = Elem.audio []
    let _map' : XmlNode list -> XmlNode = Elem.map []
    let _video' : XmlNode list -> XmlNode = Elem.video []
    let _iframe' : XmlNode list -> XmlNode = Elem.iframe []
    let _object' : XmlNode list -> XmlNode = Elem.object []
    let _picture' : XmlNode list -> XmlNode = Elem.picture []
    let _portal' : XmlNode list -> XmlNode = Elem.portal []
    let _canvas' : XmlNode list -> XmlNode = Elem.canvas []
    let _noscript' : XmlNode list -> XmlNode = Elem.noscript []
    let _script' : XmlNode list -> XmlNode = Elem.script []
    let _del' : XmlNode list -> XmlNode = Elem.del []
    let _ins' : XmlNode list -> XmlNode = Elem.ins []
    let _caption' : XmlNode list -> XmlNode = Elem.caption []
    let _colgroup' : XmlNode list -> XmlNode = Elem.colgroup []
    let _table' : XmlNode list -> XmlNode = Elem.table []
    let _tbody' : XmlNode list -> XmlNode = Elem.tbody []
    let _td' : XmlNode list -> XmlNode = Elem.td []
    let _tfoot' : XmlNode list -> XmlNode = Elem.tfoot []
    let _th' : XmlNode list -> XmlNode = Elem.th []
    let _thead' : XmlNode list -> XmlNode = Elem.thead []
    let _tr' : XmlNode list -> XmlNode = Elem.tr []
    let _button' : XmlNode list -> XmlNode = Elem.button []
    let _datalist' : XmlNode list -> XmlNode = Elem.datalist []
    let _fieldset' : XmlNode list -> XmlNode = Elem.fieldset []
    let _form' : XmlNode list -> XmlNode = Elem.form []
    let _label' : XmlNode list -> XmlNode = Elem.label []
    let _legend' : XmlNode list -> XmlNode = Elem.legend []
    let _meter' : XmlNode list -> XmlNode = Elem.meter []
    let _optgroup' : XmlNode list -> XmlNode = Elem.optgroup []
    let _option' : XmlNode list -> XmlNode = Elem.option []
    let _output' : XmlNode list -> XmlNode = Elem.output []
    let _progress' : XmlNode list -> XmlNode = Elem.progress []
    let _select' : XmlNode list -> XmlNode = Elem.select []
    let _textarea' : XmlNode list -> XmlNode = Elem.textarea []
    let _details' : XmlNode list -> XmlNode = Elem.details []
    let _dialog' : XmlNode list -> XmlNode = Elem.dialog []
    let _summary' : XmlNode list -> XmlNode = Elem.summary []
    let _slot' : XmlNode list -> XmlNode = Elem.slot []
    let _template' : XmlNode list -> XmlNode = Elem.template []
    let _math' : XmlNode list -> XmlNode = Elem.math []
    let _svg' : XmlNode list -> XmlNode = Elem.svg []

module a =
    let _accept = Attr.accept
    let _acceptCharset = Attr.acceptCharset
    let _accesskey = Attr.accesskey
    let _action = Attr.action
    let _align = Attr.align
    let _allow = Attr.allow
    let _alt = Attr.alt
    let _async = Attr.async
    let _autocapitalize = Attr.autocapitalize
    let _autocomplete = Attr.autocomplete
    let _autofocus = Attr.autofocus
    let _autoplay = Attr.autoplay
    let _background = Attr.background
    let _bgcolor = Attr.bgcolor
    let _border = Attr.border
    let _buffered = Attr.buffered
    let _capture = Attr.capture
    let _challenge = Attr.challenge
    let _charset = Attr.charset
    let _checked = Attr.checked'
    let _cite = Attr.cite
    let _class = Attr.class'
    let _code = Attr.code
    let _codebase = Attr.codebase
    let _color = Attr.color
    let _cols = Attr.cols
    let _colspan = Attr.colspan
    let _content = Attr.content
    let _contenteditable = Attr.contenteditable
    let _contextmenu = Attr.contextmenu
    let _controls = Attr.controls
    let _coords = Attr.coords
    let _crossorigin = Attr.crossorigin
    let _csp = Attr.csp
    let _data = Attr.data
    let _dataAttr = Attr.dataAttr
    let _datetime = Attr.datetime
    let _decoding = Attr.decoding
    let _default = Attr.default'
    let _defer = Attr.defer
    let _dir = Attr.dir
    let _dirname = Attr.dirname
    let _disabled = Attr.disabled
    let _download = Attr.download
    let _draggable = Attr.draggable
    let _enctype = Attr.enctype
    let _enterkeyhint = Attr.enterkeyhint
    let _for = Attr.for'
    let _form = Attr.form
    let _formaction = Attr.formaction
    let _formenctype = Attr.formenctype
    let _formmethod = Attr.formmethod
    let _formnovalidate = Attr.formnovalidate
    let _formtarget = Attr.formtarget
    let _headers = Attr.headers
    let _height = Attr.height
    let _hidden = Attr.hidden
    let _high = Attr.high
    let _href = Attr.href
    let _hreflang = Attr.hreflang
    let _httpEquiv = Attr.httpEquiv
    let _icon = Attr.icon
    let _id = Attr.id
    let _importance = Attr.importance
    let _integrity = Attr.integrity
    let _inputmode = Attr.inputmode
    let _ismap = Attr.ismap
    let _itemprop = Attr.itemprop
    let _keytype = Attr.keytype
    let _kind = Attr.kind
    let _label = Attr.label
    let _lang = Attr.lang
    let _loading = Attr.loading
    let _list = Attr.list
    let _loop = Attr.loop
    let _low = Attr.low
    let _max = Attr.max
    let _maxlength = Attr.maxlength
    let _minlength = Attr.minlength
    let _media = Attr.media
    let _method = Attr.method
    let _min = Attr.min
    let _multiple = Attr.multiple
    let _muted = Attr.muted
    let _name = Attr.name
    let _novalidate = Attr.novalidate
    let _open = Attr.open'
    let _optimum = Attr.optimum
    let _pattern = Attr.pattern
    let _ping = Attr.ping
    let _placeholder = Attr.placeholder
    let _poster = Attr.poster
    let _preload = Attr.preload
    let _radiogroup = Attr.radiogroup
    let _readonly = Attr.readonly
    let _referrerpolicy = Attr.referrerpolicy
    let _rel = Attr.rel
    let _required = Attr.required
    let _reversed = Attr.reversed
    let _role = Attr.role
    let _rows = Attr.rows
    let _rowspan = Attr.rowspan
    let _sandbox = Attr.sandbox
    let _scope = Attr.scope
    let _selected = Attr.selected
    let _shape = Attr.shape
    let _size = Attr.size
    let _sizes = Attr.sizes
    let _slot = Attr.slot
    let _span = Attr.span
    let _spellcheck = Attr.spellcheck
    let _src = Attr.src
    let _srcdoc = Attr.srcdoc
    let _srclang = Attr.srclang
    let _srcset = Attr.srcset
    let _start = Attr.start
    let _step = Attr.step
    let _style = Attr.style
    let _tabindex = Attr.tabindex
    let _target = Attr.target
    let _title = Attr.title
    let _translate = Attr.translate
    let _type = Attr.type'
    let _usemap = Attr.usemap
    let _value = Attr.value
    let _width = Attr.width
    let _wrap = Attr.wrap

    // Events
    let _onabort = Attr.onabort
    let _onafterprint = Attr.onafterprint
    let _onanimationend = Attr.onanimationend
    let _onanimationiteration = Attr.onanimationiteration
    let _onanimationstart = Attr.onanimationstart
    let _onbeforeprint = Attr.onbeforeprint
    let _onbeforeunload = Attr.onbeforeunload
    let _onblur = Attr.onblur
    let _oncanplay = Attr.oncanplay
    let _oncanplaythrough = Attr.oncanplaythrough
    let _onchange = Attr.onchange
    let _onclick = Attr.onclick
    let _oncontextmenu = Attr.oncontextmenu
    let _oncopy = Attr.oncopy
    let _oncut = Attr.oncut
    let _ondblclick = Attr.ondblclick
    let _ondrag = Attr.ondrag
    let _ondragend = Attr.ondragend
    let _ondragenter = Attr.ondragenter
    let _ondragleave = Attr.ondragleave
    let _ondragover = Attr.ondragover
    let _ondragstart = Attr.ondragstart
    let _ondrop = Attr.ondrop
    let _ondurationchange = Attr.ondurationchange
    let _onemptied = Attr.onemptied
    let _onended = Attr.onended
    let _onerror = Attr.onerror
    let _onfocus = Attr.onfocus
    let _onformchange = Attr.onformchange
    let _onforminput = Attr.onforminput
    let _onfocusin = Attr.onfocusin
    let _onfocusout = Attr.onfocusout
    let _onfullscreenchange = Attr.onfullscreenchange
    let _onfullscreenerror = Attr.onfullscreenerror
    let _onhashchange = Attr.onhashchange
    let _oninput = Attr.oninput
    let _oninvalid = Attr.oninvalid
    let _onkeydown = Attr.onkeydown
    let _onkeypress = Attr.onkeypress
    let _onkeyup = Attr.onkeyup
    let _onload = Attr.onload
    let _onloadeddata = Attr.onloadeddata
    let _onloadedmetadata = Attr.onloadedmetadata
    let _onloadstart = Attr.onloadstart
    let _onmessage = Attr.onmessage
    let _onmousedown = Attr.onmousedown
    let _onmouseenter = Attr.onmouseenter
    let _onmouseleave = Attr.onmouseleave
    let _onmousemove = Attr.onmousemove
    let _onmouseover = Attr.onmouseover
    let _onmouseout = Attr.onmouseout
    let _onmouseup = Attr.onmouseup
    let _onmousewheel = Attr.onmousewheel
    let _onoffline = Attr.onoffline
    let _ononline = Attr.ononline
    let _onopen = Attr.onopen
    let _onpagehide = Attr.onpagehide
    let _onpageshow = Attr.onpageshow
    let _onpaste = Attr.onpaste
    let _onpause = Attr.onpause
    let _onplay = Attr.onplay
    let _onplaying = Attr.onplaying
    let _onpopstate = Attr.onpopstate
    let _onprogress = Attr.onprogress
    let _onratechange = Attr.onratechange
    let _onresize = Attr.onresize
    let _onreset = Attr.onreset
    let _onscroll = Attr.onscroll
    let _onsearch = Attr.onsearch
    let _onseeked = Attr.onseeked
    let _onseeking = Attr.onseeking
    let _onselect = Attr.onselect
    let _onshow = Attr.onshow
    let _onstalled = Attr.onstalled
    let _onstorage = Attr.onstorage
    let _onsubmit = Attr.onsubmit
    let _onsuspend = Attr.onsuspend
    let _ontimeupdate = Attr.ontimeupdate
    let _ontoggle = Attr.ontoggle
    let _ontouchcancel = Attr.ontouchcancel
    let _ontouchend = Attr.ontouchend
    let _ontouchmove = Attr.ontouchmove
    let _ontouchstart = Attr.ontouchstart
    let _ontransitionend = Attr.ontransitionend
    let _onunload = Attr.onunload
    let _onvolumechange = Attr.onvolumechange
    let _onwaiting = Attr.onwaiting
    let _onwheel = Attr.onwheel
